server.port=8080
spring.application.name=idempotency-gateway

# PostgreSQL Database
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://dpg-d89fm6a8qa3s73e0n9ng-a:5432/payonce}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:payonce_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:bMX1oQTgwpkeb6fE6tBEXLEJLb8p0dQi}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# Idempotency TTL
idempotency.ttl-hours=24
idempotency.cleanup-interval-ms=3600000

# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# Logging
logging.level.com.igirepay=INFO
logging.level.org.hibernate.SQL=DEBUG